### ISSUE TITLE
2 warnings generated

### ISSUE THREAD

**Issue by KasRoudra** [cobiwave/simplefolio#133]
## The `npm install` is stucked in a loop of:
`2 warnings generated.
  g++ -o Release/obj.target/libsass/src/libsass/src/emitter.o ../src/libsass/src/emitter.cpp '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DLIBSASS_VERSION="3.5.5"' '-D_GLIBCXX_USE_C99_MATH' -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/include/node -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/src -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/openssl/config -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/openssl/openssl/include -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/uv/include -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/zlib -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/v8/include -I../src/libsass/include  -fPIC -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fPIC -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/emitter.o.d.raw   -c
  g++ -o Release/obj.target/libsass/src/libsass/src/environment.o ../src/libsass/src/environment.cpp '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DLIBSASS_VERSION="3.5.5"' '-D_GLIBCXX_USE_C99_MATH' -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/include/node -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/src -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/openssl/config -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/openssl/openssl/include -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/uv/include -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/zlib -I/data/data/com.termux/files/home/.cache/node-gyp/16.11.0/deps/v8/include -I../src/libsass/include  -fPIC -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fPIC -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/environment.o.d.raw   -c
In file included from ../src/libsass/src/environment.cpp:2:
../src/libsass/src/ast.hpp:1614:25: warning: loop variable 'numerator' creates a copy from type 'const std::basic_string<char>' [-Wrange-loop-construct]
        for (const auto numerator : numerators)
                        ^
../src/libsass/src/ast.hpp:1614:14: note: use reference type 'const std::basic_string<char> &' to prevent copying
        for (const auto numerator : numerators)
             ^~~~~~~~~~~~~~~~~~~~~~
                        &
../src/libsass/src/ast.hpp:1616:25: warning: loop variable 'denominator' creates a copy from type 'const std::basic_string<char>' [-Wrange-loop-construct]
        for (const auto denominator : denominators)
                        ^
../src/libsass/src/ast.hpp:1616:14: note: use reference type 'const std::basic_string<char> &' to prevent copying
        for (const auto denominator : denominators)
             ^~~~~~~~~~~~~~~~~~~~~~~~
                        &`

**Comment by remysabliet** [comment]
Having the same issue

**Comment by cobiwave** [comment]
Hey guys @KasRoudra @remysabliet 

Sorry for replying at this late. Do you still need some help or guidance?

Right now I am working on major updates (mostly fixing all the issues Simplefolio has).

I will let know to all the community via Discord.

**Comment by KasRoudra** [comment]
@cobiwave Thanks. But I no longer need help
