### ISSUE TITLE
Url of Page

### ISSUE THREAD

**Issue by Aman-8955** [cobiwave/simplefolio#146]
This page url is not working and this page is not founded on your url address.

**Comment by cobiwave** [comment]
Hi @Aman-8955 🙂 

Sorry for replying at this late. Do you still need some help or guidance?

Right now I am working on major updates (mostly fixing all the issues Simplefolio has).

I will let know to all the community via Discord.

**Comment by Aman-8955** [comment]
It's deployment is inactive and this site is showing not found.

**Comment by cobiwave** [comment]
HI @Aman-8955 - you can find the url here: https://the-simplefolio.netlify.app/

That's the deployment from the master branch, which is working.

You should be able to deploy your own version as well.

**Comment by Aman-8955** [comment]
Now everything is fine thank you @cobiwave
