### ISSUE TITLE
deprecated links due to profile name change

### ISSUE THREAD

**Issue by papstchaka** [cobiwave/simplefolio#148]
updated profile name leads to deprecated links throughout the project &rightarrow; see [`pull request #147`](https://github.com/cobiwave/simplefolio/pull/147) for fixing

**Comment by cobiwave** [comment]
Hi @papstchaka 

Sorry for replying at this late. Thank you very much! your PR was merged.

Right now I am working on major updates (mostly fixing all the issues Simplefolio has).

I will let know to all the community via Discord.
