### ISSUE TITLE
Script used on page scroll

### ISSUE THREAD

**Issue by DevDario** [cobiwave/simplefolio#219]
Were can I find the script used to make that page scroll effect ?

**Comment by cobiwave** [comment]
Hi @DevDario 

Library website: https://scrollrevealjs.org/

Library Script: https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js

**Comment by DevDario** [comment]
> Hi @DevDario
> 
> Library website: https://scrollrevealjs.org/
> 
> Library Script: https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js

thanks
