### ISSUE TITLE
can i host this on github pages?

### ISSUE THREAD

**Issue by jacobsayono** [cobiwave/simplefolio#222]
hi, i've got localhost:1234 working and set up. i was wondering if i can host this on a github page (https://username.github.io)

**Comment by Jethalal1234** [comment]
nope :(

**Comment by cobiwave** [comment]
Hi @jacobsayono @Jethalal1234 

I would need to create the documentation setup for different deployment services. That's a new feature.

At the moment you should be able to host your Simplefolio version on Netlify.
