### ISSUE TITLE
dark mode?

### ISSUE THREAD

**Issue by jacobsayono** [cobiwave/simplefolio#225]
is there a simple way to add a button to create a dark mode of this website?
thanks!

**Comment by cobiwave** [comment]
Hi @jacobsayono 

You should be able to do it with JavaScript and CSS (classes) for your own version of Simplefolio.

At the moment, that feature isn't part of the project's template, that's coming soon.

**Comment by cobiwave** [comment]
Example: https://codepen.io/gfscott/pen/bJEBPe
